version: '3.8'
services:
  stats-server:
    build: ./stats-server
    image: stats_image
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_database
      - POSTGRES_DB=stats_database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats_database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: ./server
    image: ewm_service_image
    container_name: ewm_service_container
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore_with_me
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
