version: '3.8'
services:
  stats-server:
    build: stats-server
    image: stats
    container_name: explore-with-me-stats
    ports:
      - "9090:9090"
    depends_on:
      - service
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: server
    image: server
    container_name: explore-with-me-ewm
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db:
    image: postgres:13.7-alpine
    container_name: explore-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
