DROP TABLE IF EXISTS stats CASCADE;

CREATE TABLE IF NOT EXISTS stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app varchar(200),
    uri varchar(200),
    ip varchar(200),
    time_stamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);